version: 0.0
os: linux
files:
  - source: / # CodeDeploy에서 전달 해 준 파일을 모두
    destination: /home/ec2-user/app/step3/zip/ # 이 폴더로 옮김
    overwrite: yes # 기존 파일 덮어쓸 지 결정

permissions: # 넘겨준 파일을 모두 ec2-user 권한을 갖도록 한다
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks: # CodeDeploy 배포 단계에서 실행할 명령어 지정
  ApplicationInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지않은 스프링 부트 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user